### ISSUE TITLE
Video files from TikTok often don't render

### ISSUE THREAD

**Issue by widardd** [wireapp/wire-webapp#8795]
Wire version: 3.17.3598 on Windows, 3.48.914 on Android
Operating system: Windows 10 1903 and Android 9 PKQ1.190319.001
Which antivirus software do you have installed: None

What steps will reproduce the problem?

1.  Share tiktok-file via wire on any platform

What is the expected result?

Rendered video file

What is the actual result?

Black box stuck at "Sending"

Please provide any additional information below. Attach a screenshot if possible.

Video file example producing this behaviour: https://drive.google.com/open?id=125BRJRBbZS_nourxStES1G3CLSOtNRfO

Re-encoding such video files fixes the issue.

**Comment by bennycode** [comment]
Issue is fixed with Wire version 3.19:

![image](https://user-images.githubusercontent.com/469989/90259923-184f8700-de4b-11ea-9df2-89de813e813f.png)

**Comment by widardd** [comment]
Not fixed, just tried it with a random tiktok-file.

Edit: This one: https://drive.google.com/file/d/1dTW9ONlcuzXBSJuISGXMiyyIKgA6-gzx/view?usp=sharing
